### ISSUE TITLE
[BUG] Figure shortcode bug

### ISSUE THREAD

**Issue by ka2590** [1bl4z3r/hermit-V2#101]
https://discourse.gohugo.io/t/why-does-a-path-that-works-for-a-markdown-image-not-work-for-the-figure-shortcode/52631/5

**Comment by 1bl4z3r** [comment]
Hi @ka2590,

Thanks for letting me know. However, it would've been better if you had raised the issue here instead. Though I understand why you've done it, and I would've done the same in your position.

You must have missed the documentation for figure shortcode implementation mentioned [here](https://1bl4z3r.github.io/hermit-V2/en/posts/the-figure-shortcode/)

```
This theme extends upon default figure shortcode to implement following features :

- Convert JPG Images on the fly to WEBP and serve WEBP images with JPG as a fallback.
- Convert WEBP Images on the fly to JPG and serve WEBP images with JPG as fallback.
- If src contains a link (starting with http/https), it will be parsed accordingly.
- 1-to-1 feature set compatiblity if you are using figure shortcode or ![]().
- To use relative paths images need to be put in a folder “assets” in the root of the folder.
```

**Comment by 1bl4z3r** [comment]
Hi @ka2590 again,

I am looking to implement what jmooring had suggested. Please see this issue for updates.

Since this requires extensive testing from my part, I hope to push out a change by this weekend.

**Comment by ka2590** [comment]
Please note I AM NOT the original author of that post. I just shared the bug as courtesy.

**Comment by 1bl4z3r** [comment]
Oh my bad. I thought you were 😅
