### ISSUE TITLE
[BUG] - Minify svg icon with hugo

### ISSUE THREAD

**Issue by xuhdev** [1bl4z3r/hermit-V2#62]
**Describe the bug**
Hugo is capable of minifying svg files: https://gohugo.io/hugo-pipes/minification/

For this to work, the svg file simply need to be treated like other assets, such as custom CSS.

**Comment by 1bl4z3r** [comment]
Hi @xuhdev,

Good day

Yes Hugo is capable, provided we supply the svg file as an unit. However in this theme (and also in original theme), SVG is provided through partial, aptly named [svg.html](https://github.com/1bl4z3r/hermit-V2/blob/main/layouts/partials/svg.html)

And SVGs are injected inline through partial call with dictionary.

```go
{{ partial "svg.html" (dict "context" . "name" $name) }}
```

Since SVG images are not independent files (i.e. it doesn't have `*.svg`) and doesn't reside in assets directory, it cannot be classified as a resource, henceforth it can't be fetched with `resources.get`.

To move SVG images to /assets and making all the necessary changes would be an uphill task, but I am still open to ideas. If you have any idea how you would wish to be implemented, let me know

**Comment by xuhdev** [comment]
I agree that `svg.html` is already optimized, but the svg favicon provided by the user could be minified just like the custom css files :)

**Comment by 1bl4z3r** [comment]
Ooh...
You must say so. I was thinking why a partial should be optimized...😅

Since favicon is in `/static`, I didn't think about making it a resource. Hold on. Let me update it

**Comment by 1bl4z3r** [comment]
Another itty-bitty change. Nothing much

```go
{{ $favicon := "images/favicon.svg" }}
{{- if (fileExists (printf "assets/%s" $favicon)) -}}
{{- with resources.Get $favicon | minify -}}
<link rel="icon" href="{{ .Permalink }}" type="image/svg+xml">
{{- end -}}
{{- else if (fileExists "static/favicon.svg") -}}
<link rel="icon" href="{{"favicon.svg" | relURL}}" type="image/svg+xml">
{{- end -}}
```

**Comment by 1bl4z3r** [comment]
Chrome being Chome, I see...😆
I just checked and you're right. Restarting Chrome defaults to ICO favicon. 

Thanks for the PR btw. Now SVG all the way...🎉

Closing this Issue.
